#!/usr/bin/env bash
RESET='\033[0m'
RED='\033[1;31m'
CYAN='\033[1;36m'

# Python
virtualenv --quiet venv/ducksoup

echo 'Running Setup of virtual environment.'

source venv/ducksoup/bin/activate
pip install --quiet -r requirements/mac.txt
ln -sf venv/${1}/bin/activate activate-ducksoup
chmod 755 activate-ducksoup

echo -e "${CYAN}Run command \`${RESET}source activate-ducksoup${CYAN}\` to activate the virtualenv,${RESET}"
